---
sidebar: sidebar 
permalink: concept-client-protocols.html 
keywords: client protocols, client version, smb version, nfs version, protocol versions, s3, smb, nfs, iscsi, cifs 
summary: Cloud Volumes ONTAP は、 iSCSI 、 NFS 、 SMB 、 S3 のクライアントプロトコルをサポートしています。 
---
= クライアントプロトコル
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP は、 iSCSI 、 NFS 、 SMB 、 S3 のクライアントプロトコルをサポートしています。



== iSCSI

iSCSI は、標準のイーサネットネットワークで実行できるブロックプロトコルです。ほとんどのクライアントオペレーティングシステムには、標準のイーサネットポートで動作するソフトウェアイニシエータが搭載されています。



== NFS

NFS は、 UNIX および Linux システム向けの従来のファイルアクセスプロトコルです。クライアントは、 NFSv3 、 NFSv4 、および NFSv4.1 プロトコルを使用して ONTAP ボリューム内のファイルにアクセスできます。ファイルアクセスは、 UNIX 形式の権限、 NTFS 形式の権限、またはその両方の組み合わせを使用して制御できます。

クライアントは、 NFS プロトコルと SMB プロトコルの両方を使用して同じファイルにアクセスできます。



== SMB

SMB は、 Windows システム向けの従来のファイルアクセスプロトコルです。クライアントは、 SMB 2.0 、 SMB 2.1 、 SMB 3.0 、および SMB 3.1.1 の各プロトコルを使用して ONTAP ボリューム内のファイルにアクセスできます。NFS と同様に、複数の形式の権限の組み合わせがサポートされています。



== S3

Cloud Volumes ONTAP は、 Microsoft Azure のスケールアウトストレージ用のオプションとして S3 をサポートしています。S3 プロトコルをサポートすると、 SVM のバケットに格納されたオブジェクトへの S3 クライアントアクセスを設定できるようになります。

現時点では、 AWS の Cloud Volumes ONTAP や Google Cloud では S3 プロトコルはサポートされていません。

https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["ONTAP で S3 オブジェクトストレージサービスを設定および管理する方法について説明します"^]。
