---
sidebar: sidebar 
permalink: reference-default-configs.html 
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: Cloud Volumes ONTAP がデフォルトでどのように設定されているかを理解すると、システムのセットアップと管理に役立ちます。特に、 ONTAP に精通している場合は、 Cloud Volumes ONTAP のデフォルト設定は ONTAP とは異なるためです。 
---
= Cloud Volumes ONTAP のデフォルト設定
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP がデフォルトでどのように設定されているかを理解すると、システムのセットアップと管理に役立ちます。特に、 ONTAP に精通している場合は、 Cloud Volumes ONTAP のデフォルト設定は ONTAP とは異なるためです。



== デフォルト値です

* Cloud Volumes ONTAP は、シングルノードシステムとして、また AWS 、 Azure 、 GCP の HA ペアとして利用できます。
* Cloud Manager は、 Cloud Volumes ONTAP の導入時にデータを提供する Storage VM を 1 つ作成します。追加の Storage VM をサポートする構成もあります。 link:task-managing-svms.html["Storage VM の管理に関する詳細情報"]。
+
Cloud Manager 3.9.5 リリース以降では、最初の Storage VM で論理スペースのレポートが有効になります。スペースが論理的に報告されると、 ONTAP は、 Storage Efficiency 機能で削減されたすべての物理スペースが使用済みと報告するようにボリュームスペースを報告します。

* Cloud Manager は、次の ONTAP 機能ライセンスを Cloud Volumes ONTAP に自動的にインストールします。
+
** CIFS
** FlexCache
** FlexClone
** iSCSI
** NetApp Volume Encryption （ライセンス使用システムまたは登録従量課金制システムの場合のみ）
** NFS
** SnapMirror
** SnapRestore
** SnapVault


* デフォルトでは、いくつかのネットワークインターフェイスが作成されます。
+
** クラスタ管理 LIF
** クラスタ間 LIF
** Azure および GCP の HA システム、 AWS のシングルノードシステム、および複数の AWS アベイラビリティゾーンの HA システム上の SVM 管理 LIF （オプション）
** ノード管理 LIF （ GCP では、この LIF がクラスタ間 LIF と結合されます）
** iSCSI データ LIF
** CIFS および NFS データ LIF
+

NOTE: EC2 の要件により、 Cloud Volumes ONTAP の LIF フェイルオーバーはデフォルトで無効になっています。LIF を別のポートに移行すると、インスタンス上の IP アドレスとネットワークインターフェイス間の外部マッピングが解除され、 LIF にアクセスできなくなります。



* Cloud Volumes ONTAP は、 HTTPS を使用してコネクタに構成バックアップを送信します。
+
バックアップにはからアクセスできます https://ipaddress/occm/offboxconfig/[] ここで、 _ipaddress_ はコネクタホストの IP アドレスです。

* Cloud Manager は、他の管理ツール（ System Manager や CLI など）とは異なるボリューム属性をいくつか設定します。
+
次の表に、 Cloud Manager がデフォルトとは異なる設定にしたボリューム属性を示します。

+
[cols="15,85"]
|===
| 属性 | Cloud Manager によって設定される値 


| オートサイズモード | 成長 


| 最大オートサイズ  a| 
1,000 パーセント


NOTE: アカウント管理者は、 [ 設定 ] ページからこの値を変更できます。



| セキュリティ形式 | CIFS ボリューム UNIX の場合は NTFS 、 NFS ボリュームの場合は NTFS 


| スペースギャランティスタイル | なし 


| UNIX 権限（ NFS のみ） | 777 
|===
+
これらの属性の詳細については、 _volume create のマニュアルページを参照してください。





== システムデータ用の内蔵ディスク

ユーザデータ用のストレージに加えて、 Cloud Manager はシステムデータ用のクラウドストレージも購入します。



=== AWS

* ノードあたり 3 本のディスクで、ブート、ルート、コアの各データに対応：
+
** ブートデータ用に 45GiB io1 ディスク
** ルートデータ用に 140GiB GP3 ディスク
** コアデータ用に 540GiB GP2 ディスク


* ブートディスクとルートディスクごとに 1 つの EBS スナップショット
* HA ペアの場合は、メディエーターインスタンス用の EBS ボリュームが 1 つで、約 8GiB です



TIP: AWS では、 NVRAM はブートディスクにあります。



=== Azure （シングルノード）

* Premium SSD ディスク × 3 ：
+
** ブートデータ用に 10 GiB のディスクを 1 台
** ルートデータ用に 140GiB のディスクが 1 つ
** NVRAM 用に 512GiB ディスクが 1 本必要です
+
Cloud Volumes ONTAP 用に選択した仮想マシンでウルトラ SSD がサポートされている場合、システムは Premium SSD ではなく 32GiB Ultra SSD を NVRAM に使用します。



* コアを節約するために 1024 GiB の標準 HDD ディスクを 1 台
* 各ブートディスクとルートディスクに 1 つの Azure Snapshot




=== Azure （ HA ペア）

* ブートボリューム用の 10GiB Premium SSD ディスク × 2 （ノードごとに 1 つ）
* ルート用の 140 GiB Premium Storage ページブロブ 2 つ ボリューム（ノードごとに 1 つ）
* コアを節約するために 1024 GiB の標準 HDD ディスク 2 台 （ノードごとに 1 つ）
* NVRAM 用 512GiB Premium SSD ディスク × 2 （各ノードに 1 つ）
* 各ブートディスクとルートディスクに 1 つの Azure Snapshot




=== Google Cloud （シングルノード）

* ブートデータ用の 10GiB SSD 永続ディスク × 1
* ルートデータ用に 64GiB SSD パーシステントディスクが 1 本
* NVRAM 用に 500GiB SSD 永続ディスクが 1 本
* コアを節約するための 315 GiB 標準永続ディスク 1 台
* ブートデータとルートデータ用の Snapshot




=== Google Cloud （ HA ペア）

* ブートデータ用の 2 本の 10GiB SSD 永続ディスク
* 64 GiB SSD の 4 本の永続的ディスクをルートデータ用に使用
* NVRAM 用に 500GiB の SSD 永続ディスクが 2 本搭載されています
* コアを節約するための 2 つの 315 GiB 標準パーシステントディスク
* メディエーターデータ用の 10GiB 標準永続ディスクが 1 本
* ブートデータとルートデータ用の Snapshot




=== ディスクが存在する場所

Cloud Manager は次のようにストレージを配置します。

* ブートデータは、インスタンスまたは仮想マシンに接続されたディスクにあります。
+
このディスクにはブートイメージが含まれており、 Cloud Volumes ONTAP では使用できません。

* システム構成とログを含むルートデータは、 aggr0 にあります。
* Storage Virtual Machine （ SVM ）ルートボリュームは aggr1 にあります。
* データボリュームも aggr1 にあります。




=== 暗号化

ブートディスクとルートディスクは、これらのクラウドプロバイダではデフォルトで暗号化が有効になるため、 Azure と Google Cloud Platform では常に暗号化されます。

キー管理サービス（ KMS ）を使用して AWS でデータ暗号化を有効にすると、 Cloud Volumes ONTAP のブートディスクとルートディスクも暗号化されます。これには、 HA ペアのメディエーターインスタンスのブートディスクが含まれます。ディスクは、作業環境の作成時に選択した CMK を使用して暗号化されます。
