---
sidebar: sidebar 
permalink: task-google-key-manager.html 
keywords: google cloud, encryption, NVE, NetApp volume encryption, KMIP, GCP, GCP KMS, key manager service, encryption 
summary: サードパーティのキー管理サービスにAzure Key Vaultを利用 
---
= GoogleのCloud Key Management Serviceを使用してキーを管理します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


を使用できます link:https://cloud.google.com/kms/docs["Google Cloud Platform のキー管理サービス（ Cloud KMS ）"^] Google Cloud Platform導入アプリケーションでONTAP 暗号化キーを保護します。

キー管理Cloud KMSは、CLIまたはONTAP REST APIを使用して有効にすることができます。Cloud Volumes ONTAP 用にCloud KMSを設定するには、まず必要があります

Cloud KMSを使用する際は、デフォルトでデータSVM LIFがクラウドキー管理エンドポイントとの通信に使用されることに注意してください。ノード管理ネットワークは、クラウドプロバイダの認証サービス（oauth2.googleapis.com）との通信に使用されます。クラスタネットワークが正しく設定されていないと、クラスタでキー管理サービスが適切に利用されません。

.前提条件
* Cloud Volumes ONTAP クラスタのノードでNVEがサポートされている必要があります
* Volume Encryption （ VE ）ライセンスがインストールされている
* Multi-tenant Encryption Key Management （ MTEKM ）ライセンスがインストールされています
* クラスタ管理者またはSVMの管理者である必要があります


.制限
* Cloud Volumes ONTAP でバージョン9.10.1以降が実行されている必要があります
* クラウドKMSはNSEとNAEには利用できません。
* MetroCluster 構成では、クラウドKMSは利用できません。
* クラウドKMSはデータSVMでのみ設定できます
* アクティブなGoogle Cloud Platformサブスクリプション


.-- 有効にします
. Google Cloud環境の場合：
+
.. 対称GCPキーリングとキーを作成します。
.. Cloud Volumes ONTAP サービスアカウント用のカスタムロールを作成します。「gcloud iam roles create kmsCustomRole -- project=_project_id_--title=_tks_custom_role_name_--description=ks.cryptoKeyVersionsGet、kms.cryptoKeyVersions.get、kms.cryptoKeyVersions.list、cloudkms.cryptoKeyVersions.useToDecrypt,cloudkms.cryptoKeyVersions.useToEncrypt,cloudkms.cryptoKeys.get,cloudkms.keyRings.get,cloudkms.locations.get,cloudkms.locations.list,resourcemanager.projects.get -stage /ga/ga/ga/ga?-stage
.. カスタムロールをCloud KMSキーとCloud Volumes ONTAP サービスアカウントに割り当てます。「gcloud kms keys add -iam-policy binding ${_key_name_}-- keyring ${_key_ring_NAME_}-- location ${_key_location_}-- member serviceAccount：${_service_account_Name_}--role_projects/customers_projects_projects_security_security_security_security_security_roles/<_project.<_security_security_account>
.. サービスアカウントのJSONキーをダウンロードします。「gcloud iam service-accounts keys create key-file --iam-account=_sa-name_@_project-id_.iam.gserviceaccount.com


. Cloud Volumes ONTAP 環境に切り替えます。
+
.. advanced権限レベルに切り替えます:'set -privilege advanced
.. データSVM用のDNSを作成DNS create -domains c._<<project>>_.internal -name-servers_server_address_-vserver_svm_name_`
.. CMEKエントリを作成します：'security key-manager external GCP enable -vserver_svm_name_project-id_project_-key-ring-name_key_ring_name_-key-ring -location_key_ring_location_-key-name_key_name_`
.. プロンプトが表示されたら、GCPアカウントのJSONキーを入力します。
.. 有効なプロセスが成功したことを確認します。「security key-manager external GCP check -vserver _svm_name _」
.. オプション：暗号化「vol create _volume_name_>-aggregate _vserver_name_-size 10G」をテストするボリュームを作成します






== トラブルシューティングを行う

トラブルシューティングが必要な場合は、上記の最後の2つの手順でREST APIのrawログをテールできます。「set d`」。「systemshell -node _node」コマンドtail -f /mroot/etc/log/mlog/kmip2_client.log
