---
sidebar: sidebar 
permalink: task-manage-aggregates.html 
keywords: aggregates, delete aggregates, add disks, view aggregates 
summary: アグリゲートの管理を自分で行うには、ディスクの追加、アグリゲートに関する情報の表示、およびアグリゲートの削除を行います。 
---
= アグリゲートを管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
アグリゲートの管理を自分で行うには、ディスクの追加、アグリゲートに関する情報の表示、およびアグリゲートの削除を行います。


CAUTION: すべてのディスクとアグリゲートは、 Cloud Manager から直接作成および削除する必要があります。これらのアクションは、別の管理ツールから実行しないでください。これにより、システムの安定性が低下し、将来ディスクを追加できなくなる可能性があります。また、クラウドプロバイダの冗長料金が発生する可能性もあります。

アグリゲートを削除する場合は、まずアグリゲート内のボリュームを削除しておく必要があります。

アグリゲートのスペースが不足している場合は、 System Manager を使用してボリュームを別のアグリゲートに移動できます。

.手順
. キャンバスページで、アグリゲートを管理する Cloud Volumes ONTAP 作業環境をダブルクリックします。
. メニューアイコンをクリックし、 [ * 詳細設定 ] > [ 高度な割り当て * ] をクリックします。
. アグリゲートの管理：
+
[cols="30,70"]
|===
| タスク | アクション 


| アグリゲートに関する情報を表示します | アグリゲートを選択し、 * Info * をクリックします。 


| 特定のアグリゲートにボリュームを作成します | アグリゲートを選択し、 * ボリュームの作成 * をクリックします。 


| アグリゲートにディスクを追加します  a| 
.. アグリゲートを選択し、*ディスクの追加*をクリックします。
.. 追加するディスクの数を選択し、 * 追加 * をクリックします。
+

TIP: アグリゲート内のディスクはすべて同じサイズである必要があります。



ifdef::aws[]



| Amazon EBS Elastic Volumesをサポートするアグリゲートの容量を増やす  a| 
.. アグリゲートを選択し、*容量を追加*をクリックします。
.. 追加する容量を入力し、*追加*をクリックします。
+
アグリゲートの容量は256GiB以上、またはアグリゲートのサイズの10%以上拡張する必要があります。

+
たとえば、アグリゲートのサイズが1.77TiBの場合、10%は181GiBです。これは256 GiBよりも小さいため、アグリゲートのサイズを256 GiB以上増やす必要があります。



endif::aws[]



| アグリゲートを削除します  a| 
.. ボリュームを含まないアグリゲートを選択し、 * Delete * をクリックします。
.. 再度 * Delete * をクリックして確定します。


|===

