---
sidebar: sidebar 
permalink: task-encrypting-volumes.html 
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption 
summary: Cloud Volumes ONTAP は、外部キー管理ツールを使用して、 NetApp Volume Encryption （ NVE ）と NetApp Aggregate Encryption （ NAE ）の両方をサポートします。外部キー管理ツールを設定すると、 NVE と NAE はデフォルトで有効になります。 
---
= ネットアップの暗号化ソリューションによるボリュームの暗号化
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Cloud Volumes ONTAP は、 NetApp Volume Encryption （ NVE ）および NetApp Aggregate Encryption （ NAE ）をサポートしています。NVE と NAE は、（ FIPS ） 140-2 に準拠したボリュームの保管データ暗号化を可能にするソフトウェアベースのソリューションです。 link:concept-security.html["これらの暗号化ソリューションの詳細については、こちらをご覧ください"]。

NVE と NAE はどちらも外部キー管理機能でサポートされています。NVE を使用する場合、 Azure Key Vault （ AKV ）または Google Cloud Key Management Service を使用して ONTAP 暗号化キーを保護することもできます。

外部キー管理ツールを設定すると、新しいアグリゲートで NAE がデフォルトで有効になります。NAE アグリゲートに含まれない新しいボリュームでは、 NVE がデフォルトで有効になります（たとえば、外部キー管理ツールを設定する前に作成された既存のアグリゲートがある場合）。

Cloud Volumes ONTAP はオンボードキー管理をサポートしていません。

Cloud Volumes ONTAP システムがネットアップサポートに登録されている必要があります。ネットアップサポートに登録されている各 Cloud Volumes ONTAP システムには、 NetApp Volume Encryption ライセンスが自動的にインストールされます。

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-adding-nss-accounts.html["Cloud Manager へのネットアップサポートサイトのアカウントの追加"^]
* link:task-registering.html["従量課金制システムの登録"]



NOTE: Cloud Manager は、中国地域のシステムに NVE ライセンスをインストールしません。

.手順
. でサポートされているキー管理ツールのリストを確認します http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]。
+

TIP: Key Managers * ソリューションを検索します。

. link:task-connecting-to-otc.html["Cloud Volumes ONTAP CLI に接続します"^]。
. 外部キー管理を設定
+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-external-key-management-overview-concept.html["手順については、 ONTAP のドキュメントを参照してください"^]。


