---
sidebar: sidebar 
permalink: task-setting-up-gcp-encryption.html 
keywords: encryption, gcp, encryption key, permissions, customer-managed, gcpencryption 
summary: Google Cloud Storage では、データがディスクに書き込まれる前に常に暗号化されますが、 Cloud Manager API を使用して、お客様が管理する暗号化キーを使用する Cloud Volumes ONTAP システムを作成できます。これらは、 Cloud Key Management Service を使用して GCP で生成および管理するキーです。 
---
= お客様が管理する暗号化キーを Cloud Volumes ONTAP で使用する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud Storage では常にデータが暗号化されてからディスクに書き込まれますが、 Cloud Manager API を使用して、 _cuser-managed 暗号化キー _ を使用する Cloud Volumes ONTAP システムを作成できます。これらは、 Cloud Key Management Service を使用して GCP で生成および管理するキーです。

.手順
. キーが格納されているプロジェクトのプロジェクトレベルで、 Cloud Manager Connector サービスアカウントの権限が正しいことを確認します。
+
権限はから提供されます https://mysupport.netapp.com/site/info/cloud-manager-policies["Cloud Manager YAML ファイル"^] デフォルトでは、 Cloud Key Management Service に別のプロジェクトを使用する場合は適用できません。

+
権限は次のとおりです。

+
[source, yaml]
----
- cloudkms.cryptoKeyVersions.list
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
----
. のサービスアカウントを確認します https://cloud.google.com/iam/docs/service-agents["Google Compute Engine Service Agent"^] キーに対する Cloud KMS の暗号化 / 復号化権限があることを確認します。
+
サービスアカウントの名前は、「 service-[SERVICE_PROJECT_NUMBER_@compute-system.iam.gserviceaccount.com 」という形式で指定します。

+
https://cloud.google.com/kms/docs/iam#granting_roles_on_a_resource["Google Cloud のドキュメント：「 Using IAM with Cloud KMS - Granting roles on a resource"]

. 「 /GCP/VSA/meta/META/GCP-encryption-keys 」 API 呼び出しの get コマンドを呼び出すか、 GCP コンソールのキーで「 Copy Resource Name 」を選択して、キーの「 id 」を取得します。
. お客様が管理する暗号化キーを使用してオブジェクトストレージにデータを階層化する場合、 Cloud Manager は永続ディスクの暗号化に使用されるキーと同じキーを使用します。キーを使用するには、まず Google Cloud Storage バケットを有効にする必要があります。
+
.. 次の手順に従って、 Google Cloud Storage サービスエージェントを検索します https://cloud.google.com/storage/docs/getting-service-agent["Google Cloud ドキュメント：「 Getting the Cloud Storage service agent"^]。
.. 暗号化キーに移動し、 Cloud KMS 暗号化 / 復号化権限を持つ Google Cloud Storage サービスエージェントを割り当てます。


+
詳細については、を参照してください https://cloud.google.com/storage/docs/encryption/using-customer-managed-keys["Google Cloud のドキュメント：「 Using customer-managed encryption keys"^]

. 作業環境を作成するときは、 API 要求で "GcpEncryption" パラメータを使用します。
+
* 例 *

+
[source, json]
----
"gcpEncryptionParameters": {
    "key": "projects/project-1/locations/us-east4/keyRings/keyring-1/cryptoKeys/generatedkey1"
  }
----


を参照してください https://docs.netapp.com/us-en/cloud-manager-automation/index.html["Cloud Manager 自動化に関するドキュメント"^] "GcpEncryption" パラメータの使用方法の詳細については、を参照してください。
